name: Build OpenWRT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python2 python2.7-dev python3 unzip wget \
          python3-distutils python3-setuptools rsync subversion swig time \
          xsltproc zlib1g-dev python-is-python3

      - name: 更新 feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 配置固件
        run: |
          make defconfig
          # 这里可以添加其他配置命令

      - name: 编译固件
        run: |
          make -j$(nproc) V=s

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: bin/targets/
          retention-days: 5